### ISSUE TITLE
Review from a Web Dev Perspective

### ISSUE THREAD

**Issue by furkanesenn** [Notenlish/notenlish.github.io#1]
- Font'ları yerel olarak depolayıp servis etmelisin, daha yüksek performans sunuyor. (transfonter.org sitesini kullanabilrisin)
- Scriptleri defer ve async atribütleri ile asenkronize biçimde yükleyebilrisin.
- Şu garip media queryler...
- CSS dosyasını adam et
-

**Comment by Notenlish** [comment]
Closing the issue
https://github.com/Notenlish/notenlish.github.io/commit/07ff534f6ec17fe0afd671720d3f9a335b2137d4
